apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "frontendakscluste"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "frontendakscluste"
    spec:
      containers:
        - name: "frontendakscluste"
          image: "testres001.azurecr.io/frontendakscluste"
          ports:
          - containerPort: 80