on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n testres001 -g testres0018cef-rg --location "West US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n testres001 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n testres001 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n testres001 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: testres001.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote-mysql" -f  "azure-vote-mysql/Dockerfile" -t testres001.azurecr.io/frontendakscluste:${{ github.sha }}
        docker push testres001.azurecr.io/frontendakscluste:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_frontendakscluste_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep frontendakscluste0284 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace frontendakscluste0284`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: frontendakscluste0284
        container-registry-url: testres001.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: frontendakscdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: frontendakscluste0284
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          testres001.azurecr.io/frontendakscluste:${{ github.sha }}
        imagepullsecrets: |
          frontendakscdockerauth